name: Update README with Blog Posts

on:
  schedule:
    - cron: '0 * * * *' # This runs the action every hour; you can modify the time interval as needed.
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README with Dev.to blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@mr.robot.meaw" # Replace with your blog feed URL (e.g., from Medium, Dev.to, or other platforms)
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated blog post list"
          git push
